# IMPORTANT before start: Create global docker network using:
# $ docker network create main-nginx-proxy

version: "3"

services:
   nginx:
      image: nginxproxy/nginx-proxy:alpine
      container_name: MNP_nginx-proxy
      environment:
         - ENABLE_IPV6=true
      ports:
         - "80:80"
         - "443:443"
      volumes:
         - "/var/run/docker.sock:/tmp/docker.sock:ro"
         - "./volumes/certs:/etc/nginx/certs"
         - "./volumes/vhost:/etc/nginx/vhost.d"
         - "./volumes/html:/usr/share/nginx/html"
         - "./docker/nginx/conf/custom.conf:/etc/nginx/conf.d/custom.conf:ro"
         # - "./docker/nginx/vhost/example.com.conf:/etc/nginx/vhost.d/example.com.conf:ro"
      labels:
         com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx: "true"
      networks:
         - main-nginx-proxy
      restart: unless-stopped

   acme:
      image: nginxproxy/acme-companion:2.2
      container_name: MNP_acme-companion
      volumes_from:
         - nginx
      volumes:
         - "./volumes/acme:/etc/acme.sh"
         - "/var/run/docker.sock:/var/run/docker.sock"
      environment:
         - NGINX_PROXY_CONTAINER=MNP_nginx-proxy
         - DEFAULT_EMAIL=info@company.com
      depends_on:
         - nginx
      networks:
         - main-nginx-proxy
      restart: unless-stopped

networks:
   main-nginx-proxy:
      external: true
